// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingPlatform.Data;

#nullable disable

namespace TestingPlatform.Migrations
{
    [DbContext(typeof(AppDdContext))]
    partial class AppDdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("TestingPlatform.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VkProfileLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vanya123@mail.com",
                            FirstName = "Иван",
                            LastName = "Иванов",
                            Login = "vanya123",
                            MiddleName = "Иванович",
                            Phone = "+71234567890",
                            VkProfileLink = "http://vk.com/vanya123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@mail.com",
                            FirstName = "Мария",
                            LastName = "Иванова",
                            Login = "maria",
                            MiddleName = "Ивановна",
                            Phone = "+71234567899",
                            VkProfileLink = "http://vk.com/vanya123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
